name: Build GameCube DOL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

- name: Install devkitPro
  run: |
    sudo apt-get update
    sudo apt-get install -y git wget tar
    wget https://apt.devkitpro.org/install-devkitpro-pkg.deb
    sudo dpkg -i install-devkitpro-pkg.deb
    sudo apt-get update
    sudo apt-get install -y devkitPPC
          

      - name: Build DOL
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameCubeClient
          path: GameCubeClient.dol
