name: Build GameCube DOL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install devkitPPC
        run: |
          sudo apt-get update
          sudo apt-get install -y devkitpro-devkitPPC

      - name: Build DOL
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameCubeClient
          path: GameCubeClient.dol
